// TODO Implement this library.
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaoGRdFdN_OJ0zaAvxuxpqA5TzHNcMRP8',
    appId: '1:298151660289:web:67f0b248c38aded4f7e900',
    messagingSenderId: '298151660289',
    projectId: 'eventmanagement-e099d',
    authDomain: 'eventmanagement-e099d.firebaseapp.com',
    storageBucket: 'eventmanagement-e099d.firebasestorage.app',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA98pYLTQlo2lXoQfj6HwsJLjMtIPuo0c',
    appId: '1:298151660289:android:e2daf212cd2c440bf7e900',
    messagingSenderId: '298151660289',
    projectId: 'eventmanagement-e099d',
    storageBucket: 'eventmanagement-e099d.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdu-CxWrbpxsDKLaA3b_lWIeb-YvwBgtY',
    appId: '1:298151660289:ios:3ca80829f50e8398f7e900',
    messagingSenderId: '298151660289',
    projectId: 'eventmanagement-e099d',
    storageBucket: 'eventmanagement-e099d.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdu-CxWrbpxsDKLaA3b_lWIeb-YvwBgtY',
    appId: '1:298151660289:ios:3ca80829f50e8398f7e900',
    messagingSenderId: '298151660289',
    projectId: 'eventmanagement-e099d',
    storageBucket: 'eventmanagement-e099d.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaoGRdFdN_OJ0zaAvxuxpqA5TzHNcMRP8',
    appId: '1:298151660289:web:4049ffdd4b231924f7e900',
    messagingSenderId: '298151660289',
    projectId: 'eventmanagement-e099d',
    authDomain: 'eventmanagement-e099d.firebaseapp.com',
    storageBucket: 'eventmanagement-e099d.firebasestorage.app',
  );
}
